FROM ckan/ckan-base-datapusher:0.0.19

USER root

# Install xlrd and openpyxl to support Excel (.xls and .xlsx) file ingestion in DataPusher/messytables
RUN pip install xlrd==1.2.0 openpyxl

# Switch back to the default user if defined, or keep as root if necessary.
# In official CKAN datapusher, it runs under a non-root user (www-data) by default.
USER www-data
